blog/urls.py
#-*- coding: utf-8 -*-
from django.urls import path, re_path
from blog.views import UserPostListView, PostCreateView, PostDeleteView, PostUpdateView, post_detail_view, HomePostListViewAllUsers, gallery_view
from . import views


urlpatterns = [
    path('home/', HomePostListViewAllUsers.as_view(), name='blog-home-2'),
    path('', views.index, name='blog-home'),#LOGIN_REDIRECT_URL = 'blog-home' в settings.py (возможно переделать индексную страницу) name='index-home'
    path('posts/user/<str:username>/', UserPostListView.as_view(), name='user-posts-list'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    #путь для кода ниже: http://127.0.0.1:8000/post/1/kak-sozdavat-ukrasheniya-iz-smolyi/detail/
    #path('post/<int:pk>/detail/', PostDetailView.as_view(), name='post-detail'),# добавить slug после id <slug:slug>/
    path('post/<int:pk>/detail/', views.post_detail_view, name='post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('gallery/', gallery_view, name='gallery'),
]

#16. Пропишем форму в сам шаблон удаления записи.

cart/urls.py
from django.urls import path
from . import views

from django.urls import re_path
from . import views
app_name = 'cart'
urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'
urlpatterns = [
    path('catalog-list/', views.product_list, name='product_list'),
    path('product/save/', views.save_products_is_ajax, name='product-save'),
    path('catalog-list/saved-products/', views.all_save_view_products, name='all-save'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('catalog-list/order/', views.product_list_order, name='product_list_order'),
    path('<slug:category_slug>/order/', views.product_list_order, name='product_list_by_category_order'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create_order/', views.order_create, name='order_create'), 
    ]

site_honey/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('allauth.urls')),

    # здесь делаем только перенаправление на файл url.py приложения
    path('', include("blog.urls")),
    path('cart/', include("cart.urls")),
    path('orders/',include("orders.urls", namespace="orders")),
    path('catalog/', include("catalog.urls", namespace="catalog")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

cart/forms.py
from  django import forms
 
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 2)]
 
 
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int, label='Количество')
    update = forms.BooleanField(required=False, initial=True,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import redirect, get_object_or_404, render
from django.views.decorators.http import require_POST
 
from catalog.models import Product
from .cart import Cart
from .forms import CartAddProductForm
# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "catalog/base.html" %}
{% load static %}
 
{% block title %}
    Корзина товаров
{% endblock %}
 
{% block content %}
    <h1>Твоя корзина</h1>

    <div class="modal">
        <a href="/catalog/catalog-list/">
            <button class="close">Вернуться в каталог</button>
        </a>

        <a href="{% url 'orders:order_create' %}" ><button class="close">Заказ</button></a>

        <div class="modal-content">
            {% for item in cart %}
            {% with product=item.product %}
            <div class="product-favorites">
                <a href="{{ product.get_absolute_url }}">
                    <img src="
                            {% if product.image %}{{ product.image.url }}{% endif %}">
                </a>
                <h3>{{ product.name }}</h3>
                <p class="price-favorites">{{ item.price }} р.</p>
                <a href="{% url 'cart:cart_remove' product.id %}">Удалить</a>
                <td>
                    <form action="{% url 'cart:cart_add' product.id %}"
                          method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        
                        {% csrf_token %}
                    </form>
                </td>
            </div>
            {% endwith %}
        {% endfor %}

        <td class="num">Итого: {{ cart.get_total_price }} р.</td>
        </div>
    </div>

<!--Создать обработчик контента для текущей корзины покупок
    <table class="cart">
        <thead>
        <tr>
            <th>Фото</th>
            <th>Название</th>
            <th>Количество</th>
            <th>Удаление</th>
            <th>Цена за шт.</th>
            <th>Общая стоимость</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                    {% if product.image %}{{ product.image.url }}{% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>
                        <a href="{% url 'cart:cart_remove' product.id %}">Удалить</a>
                    </td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'catalog:product_list' %}" class="button button-more">Вернуться</a>
        <a href="#" class="button button-more">В начало</a>
    </p>
    -->
{% endblock %} 