blog/urls.py
#-*- coding: utf-8 -*-
from django.urls import path, re_path
from blog.views import UserPostListView, PostCreateView, PostDeleteView, PostUpdateView, post_detail_view, HomePostListViewAllUsers, gallery_view
from . import views


urlpatterns = [
    path('home/', HomePostListViewAllUsers.as_view(), name='blog-home-2'),
    path('', views.index, name='blog-home'),#LOGIN_REDIRECT_URL = 'blog-home' в settings.py (возможно переделать индексную страницу) name='index-home'
    path('posts/user/<str:username>/', UserPostListView.as_view(), name='user-posts-list'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    #путь для кода ниже: http://127.0.0.1:8000/post/1/kak-sozdavat-ukrasheniya-iz-smolyi/detail/
    #path('post/<int:pk>/detail/', PostDetailView.as_view(), name='post-detail'),# добавить slug после id <slug:slug>/
    path('post/<int:pk>/detail/', views.post_detail_view, name='post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('gallery/', gallery_view, name='gallery'),
]

#16. Пропишем форму в сам шаблон удаления записи.

catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'
urlpatterns = [
    path('catalog-list/', views.product_list, name='product_list'),
    path('product/save/', views.save_products_is_ajax, name='product-save'),
    path('catalog-list/saved-products/', views.all_save_view_products, name='all-save'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('catalog-list/order/', views.product_list_order, name='product_list_order'),
    path('<slug:category_slug>/order/', views.product_list_order, name='product_list_by_category_order'),
]

site_honey/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('allauth.urls')),

    # здесь делаем только перенаправление на файл url.py приложения
    path('', include("blog.urls")),
    path('cart/', include("cart.urls")),
    path('orders/',include("orders.urls", namespace="orders")),
    path('catalog/', include("catalog.urls", namespace="catalog")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from ckeditor.fields import RichTextField
#from django.utils.text import slugify
from pytils.translit import slugify #(сторонняя библиотека автозаполнения slug лучше использувать стандартную выше)
# pip install pytils
# postgresql - нужна

#from django.template.defaultfilters import slugify
from django.db.models.signals import pre_save #Сохранение до создания
from django.dispatch import receiver
# Create your models here.
# Класс

class Post(models.Model):
    """
    class - значит поддерживает методы
    модель содержит поля
    поля имеют настройки поведения
    """
    # мета опции
    class Meta:
        verbose_name = 'Создать пост'
        verbose_name_plural = 'Создать посты'
    # Поля модели
    title =models.CharField(max_length=200, help_text="не более 200 символов", db_index=True, verbose_name='Введите заголовок поста') # настройки полей
    # content = models.TextField(max_length=5000, blank=True, null=True, help_text="не более 5000 символов")
    content = RichTextField(max_length=5000, blank=True, null=True, help_text="не более 5000 символов")
    date_created = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='blog_cards/%Y/%m/%d', blank=True, null=True)
    date_updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE) # null=True если анонимный пользователь create article
    # в url при использовании slug обязательно добавлять id + get_absolute_url()
    slug = models.SlugField(max_length=50) # unique=True для уникальности (подумать)
    likes_post = models.ManyToManyField(User, related_name='post_likes', blank=True, verbose_name='Лайки')
    #reply = models.ForeignKey('self', null=True, related_name='reply_ok', on_delete=models.CASCADE)
    saves_posts = models.ManyToManyField(User, related_name="blog_posts_save", blank=True, verbose_name='Сохранённые посты пользователя')


    """
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)
    """


    def total_likes_post(self):
        return self.likes_post.count()
    
    def total_saves_posts(self):
        return self.saves_posts.count()

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


    # методы модели
    def __str__(self):
        return self.title
    




@receiver(pre_save, sender=Post) #в декораторе указываем сигнал и с чем работать
def prepopulated_slug(sender, instance, **kwargs):
    instance.slug = slugify(instance.title)

""" Модель комментариев блога """
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments_blog", on_delete=models.CASCADE)
    name_author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=255)
    date_created = models.DateTimeField(auto_now_add=True)
    likes_comment = models.ManyToManyField(User, related_name="likes_blog_comment", blank=True)
    reply_comment = models.ForeignKey('self', null=True, related_name="replies_comment", on_delete=models.CASCADE)
    
    def total_likes_comment(self):
        return self.likes_comment.count()
    
    def __str__(self):
        return "%s - %s - %s" %(self.post.title, self.name_author, self.id)
    
    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})
    

# модель отзывов из социальных сетей
class Review(models.Model):
    image = models.ImageField(upload_to='reviews')

    def __str__(self):
        return self.image.name

templates/templates_project/base.html
{# html импорты bootstrap, js, jquery и тд. для всего проекта #}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/media.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css" integrity="sha512-OTcub78R3msOCtY3Tc6FzeDJ8N9qvQn1Ph49ou13xgA9VsH9+LRxoFU6EqLhW4+PKRfU+/HReXmSZXHEkpYoOA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.js" integrity="sha512-E+gDQcIvNXE60SjCS38ysf1mGh4ObBpKcUOp0oEaHQHQAdaN2p7GelOpgEdpTuCLoIJyLkNXiqFZbyD9Ak/Ygw==" crossorigin="anonymous"></script>
</head>

<body>
    {% block content %}
        {% block navigation %}
        {% endblock %}
    {% endblock %}
    <script>
        // Mobile nav button
        const navBtn = document.querySelector('.mobile-nav-btn');
        const nav = document.querySelector('.mobile-nav');
        const menuIcon = document.querySelector('.nav-icon');
        const fade = document.querySelector('.mobile-nav-fade');

        navBtn.onclick = function() {
            nav.classList.toggle('mobile-nav--open');
            fade.classList.toggle('mobile-nav-fade--open');
            menuIcon.classList.toggle('nav-icon--active');
            document.body.classList.toggle('no-scroll');
        };

        fade.onclick = function() {
            nav.classList.toggle('mobile-nav--open');
            fade.classList.toggle('mobile-nav-fade--open');
            menuIcon.classList.toggle('nav-icon--active');
            document.body.classList.toggle('no-scroll');
        };

    </script>
    

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js" integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <script>
        $(document).ready(function() {
            $('.owl-carousel').owlCarousel({
                /*бесконечная карусель*/
                responsive: {
                    // breakpoint from 0 up
                    0: {
                        items: 2,
                        margin: 32,
                        loop: true,
                        dots: false,
                        autoplay: true,
                        //stagePadding: 90,
                    },
                    // breakpoint from 480 up
                    601: {
                        items: 3,
                        margin: 32,
                        loop: true,
                        dots: false,
                        autoplay: true,
                    },
                    // breakpoint from 768 up
                    1001: {
                        items: 3,
                        margin: 48,
                        loop: true,
                        dots: false,
                        autoplay: true,
                    }
                }
            });
        });

    </script>
    <script>
        $(document).ready(function() {
            $(".gallery a").fancybox();

        });

    </script>
    <script>
        const sidebar = document.querySelector('.sidebar');
        const toggleBtn = document.querySelector('.toggle-btn');
        const categories = document.querySelector('.catrgories');
        toggleBtn.addEventListener('click', function() {
            sidebar.classList.toggle('open');
        });
    </script>
    




    <script>
        $(function () {

          /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
          $("#id_image").change(function () {
            if (this.files && this.files[0]) {
              var reader = new FileReader();
              reader.onload = function (e) {
                $("#image").attr("src", e.target.result);
                $("#modalCrop").modal('show');
              }
              reader.readAsDataURL(this.files[0]);
            }
          });

          /* SCRIPTS TO HANDLE THE CROPPER BOX */
          var $image = $("#image");
          var cropBoxData;
          var canvasData;
          $("#modalCrop").on("shown.bs.modal", function () {
            $image.cropper({
              viewMode: 1,
              aspectRatio: 1/1,
              minCropBoxWidth: 200,
              minCropBoxHeight: 200,
              ready: function () {
                $image.cropper("setCanvasData", canvasData);
                $image.cropper("setCropBoxData", cropBoxData);
              }
            });
          }).on("hidden.bs.modal", function () {
            cropBoxData = $image.cropper("getCropBoxData");
            canvasData = $image.cropper("getCanvasData");
            $image.cropper("destroy");
            location.reload();
          });

          $(".js-zoom-in").click(function () {
            $image.cropper("zoom", 0.1);
          });

          $(".js-zoom-out").click(function () {
            $image.cropper("zoom", -0.1);
          });

          /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
          $(".js-crop-and-upload").click(function () {
            var cropData = $image.cropper("getData");
            // console.log(cropData);
            $("#id_x").val(cropData["x"]);
            $("#id_y").val(cropData["y"]);
            $("#id_height").val(cropData["height"]);
            $("#id_width").val(cropData["width"]);
            $("#formUpload").submit();
          });

        });
      </script>

      <script type="text/javascript">

       $(document).ready(function(event){

         // $("#chat-box").scrollTop($("#chat-box")[0].scrollHeight);

         // LIKE POSTS





         // SAVE Product

         $(document).on('click','#save',function(event){
           event.preventDefault();
           var id = $(this).attr('value');
           $.ajax({
             type: 'POST',
             url: "{% url 'catalog:product-save' %}",
             data: {id, 'csrfmiddlewaretoken':'{{ csrf_token }}'},
             dataType: 'json',
             success: function(response){
               $('#save-section').html(response['form']);
               console.log($('#save-section').html(response['form']));
             },
             error: function(rs, e){
               console.log(rs.responseText);
             },
           });
         });

         // COMMENT FORM

         $(document).on('submit','.comment-form', function(event){
           event.preventDefault();
           console.log($(this).serialize());
           $.ajax({
             type: 'POST',
             url: $(this).attr('action'),
             data: $(this).serialize(),
             dataType: 'json',
             success: function(response){
               $('.main-comment-section').html(response['form']);
               console.log(response['form'])
               $('textarea').val('');
             },
             error: function(rs, e){
               console.log(rs.responseText);
             },
           });
         });

         // REPLY FORM

         $(document).on('submit','.reply-form', function(event){
           event.preventDefault();
           console.log($(this).serialize());
           $.ajax({
             type: 'POST',
             url: $(this).attr('action'),
             data: $(this).serialize(),
             dataType: 'json',
             success: function(response){
               $('.main-comment-section').html(response['form']);
               console.log(response['form'])
               $('textarea').val('');
             },
             error: function(rs, e){
               console.log(rs.responseText);
             },
           });
         });

       });


      </script>
<!--было
<script>
  function addToFavorites() {
    document.getElementById("save").src = "{% static 'img/heart_red.png' %}";
}
</script>-->
<script>
  function addToFavorites() {
    var csrfToken = document.getElementsByName('csrfmiddlewaretoken')[0].value;
    var productId = document.getElementById('save').value;
    var heartImg = document.getElementById("heart");
      
    var xhr = new XMLHttpRequest();
    xhr.open('POST', '{% url "catalog:product-save" %}', true);
    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    xhr.setRequestHeader('X-CSRFToken', csrfToken);
      
    xhr.onreadystatechange = function() {
        if (xhr.readyState === 4 && xhr.status === 200) {
            var response = JSON.parse(xhr.responseText);
            
            if (response.saved) {
                heartImg.src = "{% static 'img/heart_red.png' %}";
            } else {
                heartImg.src = "{% static 'img/heart.png' %}";
            }
        }
    };
      
    xhr.send("id=" + productId);
}

</script>
</body>

</html>