blog/urls.py
#-*- coding: utf-8 -*-
from django.urls import path, re_path
from blog.views import UserPostListView, PostCreateView, PostDeleteView, PostUpdateView, post_detail_view, HomePostListViewAllUsers, gallery_view
from . import views


urlpatterns = [
    path('home/', HomePostListViewAllUsers.as_view(), name='blog-home-2'),
    path('', views.index, name='blog-home'),#LOGIN_REDIRECT_URL = 'blog-home' в settings.py (возможно переделать индексную страницу) name='index-home'
    path('posts/user/<str:username>/', UserPostListView.as_view(), name='user-posts-list'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    #путь для кода ниже: http://127.0.0.1:8000/post/1/kak-sozdavat-ukrasheniya-iz-smolyi/detail/
    #path('post/<int:pk>/detail/', PostDetailView.as_view(), name='post-detail'),# добавить slug после id <slug:slug>/
    path('post/<int:pk>/detail/', views.post_detail_view, name='post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('gallery/', gallery_view, name='gallery'),
]

#16. Пропишем форму в сам шаблон удаления записи.

cart/urls.py
from django.urls import path
from . import views

from django.urls import re_path
from . import views
app_name = 'cart'
urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'
urlpatterns = [
    path('catalog-list/', views.product_list, name='product_list'),
    path('product/save/', views.save_products_is_ajax, name='product-save'),
    path('catalog-list/saved-products/', views.all_save_view_products, name='all-save'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('catalog-list/order/', views.product_list_order, name='product_list_order'),
    path('<slug:category_slug>/order/', views.product_list_order, name='product_list_by_category_order'),
]

site_honey/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('allauth.urls')),

    # здесь делаем только перенаправление на файл url.py приложения
    path('', include("blog.urls")),
    path('cart/', include("cart.urls")),
    path('orders/',include("orders.urls", namespace="orders")),
    path('catalog/', include("catalog.urls", namespace="catalog")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('catalog:product_list_by_category', args=[self.slug])
    
    def get_absolute_url_order(self):
        return reverse('catalog:product_list_by_category_order', args=[self.slug])
    
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = RichTextField(max_length=1000, blank=True, null=True, help_text="не более 1000 символов")
    price = models.DecimalField(max_digits=10, decimal_places=0)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    saved_products = models.ManyToManyField(
        User, related_name="catalog_products_save", blank=True, verbose_name='Сохранённые товары пользователя'
    )
 
    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'),)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def total_saved_products(self):
        return self.saved_products.count()
 
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('catalog:product_detail', args=[self.id, self.slug])

catalog/views.py
from django.shortcuts import render, get_object_or_404
from catalog.models import Category, Product
from cart.forms import CartAddProductForm
from django.contrib.auth.decorators import login_required

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'catalog/product/list.html',
                  {'category': category, 'categories': categories,
                   'products': products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'catalog/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})

def product_list_order(request, category_slug=None):
    category = None
    categories = Category.objects.filter(products__available=False).distinct()
    products = Product.objects.filter(available=False)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'catalog/product/list_order.html',
                  {'category': category, 'categories': categories,
                   'products': products})

@login_required
def all_save_view_products(request):
    user = request.user
    saved_products = user.catalog_products_save.all()
    context = {'saved_products': saved_products}
    return render(request, 'catalog/saved_products.html', context)


"""
было
@login_required
def save_products_is_ajax(request):
    product = get_object_or_404(Product, id=request.POST.get("id"))
    saved = False
    if product.saved_products.filter(id=request.user.id).exists():
        product.saved_products.remove(request.user)
        saved = False
    else:
        product.saved_products.add(request.user)
        saved = True
    context = {
        'product': product,
        'total_saved_products': product.total_saved_products(),
        'saved': saved
    }

    if request.is_ajax():
        html = render_to_string('catalog/save_section.html',
                                context,
                                request=request)
        return JsonResponse({'form':html})
"""

@login_required
def save_products_is_ajax(request):
    product = get_object_or_404(Product, id=request.POST.get("id"))
    saved = False
    if product.saved_products.filter(id=request.user.id).exists():
        product.saved_products.remove(request.user)
        saved = False
    else:
        product.saved_products.add(request.user)
        saved = True
    context = {
        'product': product,
        'total_saved_products': product.total_saved_products(),
        'saved': saved
    }

    html = render_to_string('catalog/save_section.html', context, request=request)
    return JsonResponse({'form': html})

catalog/templates/catalog/product/detail.html
{% extends 'catalog/base.html' %}

{% load static %}

{% block title %}
  {% if product %}{{ product.name }}{% endif %}
{% endblock %}

{% block content_catalog_detail %}
<header class="header-catalog">
    {% block navigation %}
    {% include 'catalog/navbar-catalog.html' %}
    {% endblock %}
    </header>
<section class="section_detail">
    <div class="container">
        <div class="micro_navbar">
            <a href="/catalog/catalog-list/"><button class="detail_catalog">Вернуться в каталог</button></a>
        </div>
        
        <div class="about-us">
            {% if messages %}{{ message }}{% endif %}
            <img class="img_detail" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'catalog/img/no_image.png' %}{% endif %}">
            <div class="about-us__desc">
                <h3 class="about-us__title">{{ product.name }}</h3>
                <p>{{ product.price }} р.</p>
                <div class="about-us__detail">
                <p>{{ product.description| safe }}</p>
                </div>
                <footer class="card__footer">
                    
                    <form id="cart-form" action="{% url 'cart:cart_add' product.id %}" method="POST">
                        <label for="quantity" class="quantity-label"></label>
                        <!--<input type="number" name="quantity" id="quantity" class="quantity-input" value="1" min="1">-->
                        
                        {{ cart_product_form }}
                        {% csrf_token %}
                        <button type="submit" class="button button-more" id="add-to-cart-btn">В корзину</button>
                    </form>
                    <div class="card__rating">
                        <img src="{% static 'img/heart.png' %}" alt="heart">
                    </div>
                </footer>
            </div>
            

            
        </div>
    </div>
</section>
{% endblock %}

catalog/templates/catalog/product/list.html
{% extends 'catalog/base.html' %}

{% load static %}


{% block content_catalog %}
<header class="header-catalog">
    {% block navigation %}
    {% include 'catalog/navbar-catalog.html' %}
    {% endblock %}
    </header>
<section class="section-catalog">
    <div class="container-catalog">
        <div class="nav_cat">
        <button id="sidebar" class="toggle-btn">Категории <img src="{% static 'img\icons\arrow-right-form.svg' %}" class="arrow-icon"></i></button>
        <div class="sidebar">
            
            <ul class="categories">
                <li>
                    <a href="{% url 'catalog:product_list' %}">Все категории</a>
                </li>
                {% for c in categories %}
                    <li>
                        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                {% endfor %}
            

            <li class="line_cart">
                {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                        
                        <a href="{% url 'cart:cart_detail' %}">
                            В корзине: {{ total_items }},</br>
                            Сумма: {{ cart.get_total_price }}р.
                        </a>
                    </li>
                    {% else %}
                        <li>Корзина пуста :(</li>
                    {% endif %}
                {% endwith %}
                    
                </ul>
        </div>
    </div>
        <div class="catalog">
            {% for product in products %}
            <div class="product">
               
                    <img src="{{ product.image.url }}" alt="Product 1">
                    
                
                <h4>{% if product %}{{ product.name }}{% endif %}</h4>
            <footer class="card__footer">
                <p>{{ product.price }} р.</p>
                <p>В наличии: {{ product.stock }}</p>
                <div id="save-section" class="card__rating">
                    {% include 'catalog/save_section.html' %}
                    <!--<img src="{% static 'img/heart.png' %}" alt="heart">-->
                </div>
            </footer>
            <div class="detail_catalog_date">
                <a href="{{ product.get_absolute_url }}"><button class="detail_catalog">Подробнее</button></a>
                
                <p>{{ product.created|date:'d.m.y' }}г.</p>
            </div>
            </div>
            {% endfor %}
        </div>
        
    </div>
</section>
{% endblock %}

catalog/templates/catalog/product/list_order.html
{% extends 'catalog/base.html' %}

{% load static %}


{% block content_catalog %}
<header class="header-catalog">
    {% block navigation %}
    {% include 'catalog/navbar-catalog.html' %}
    {% endblock %}
    </header>
<section class="section">
    <div class="container-catalog">
        <div class="nav_cat">
            <button id="sidebar" class="toggle-btn">Категории <img src="{% static 'img\icons\arrow-right-form.svg' %}" class="arrow-icon"></i></button>
            <div class="sidebar">
                
                <ul class="categories">
                    <li>
                        <a href="{% url 'catalog:product_list_order' %}">Все категории</a>
                    </li>
                    {% for c in categories %}
                        <li>
                            <a href="{{ c.get_absolute_url_order }}">{{ c.name }}</a>
                        </li>
                    {% endfor %}
                        
                    </ul>
            </div>
        </div>
        <div class="catalog">
            {% for product in products %}
            
            <div class="product">
               
                    <img src="{{ product.image.url }}" alt="Product 1">
                    
                
                <h4>{% if product %}{{ product.name }}{% endif %}</h4>
            <footer class="card__footer">
                <p>{{ product.price }} р.</p>
                <div class="card__rating">
                    <img src="{% static 'img/heart.png' %}" alt="heart">
                </div>
            </footer>
            </div>
            
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}